apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: cambiar-image-pull-policy
spec:
  rules:
    - name: cambiar-image-pull-policy
      match:
        any:
        - resources:
            kinds:
            - Pod
      exclude:
        any:
        - resources:
            namespaces:
            - argocd
            - ingress-nginx
            - default
            - policy-reporter
      mutate:
        patchStrategicMerge:
          spec:
            containers:
              # match images which end with :latest
              - (image): "*:latest"
                # set the imagePullPolicy to "IfNotPresent"
                imagePullPolicy: "IfNotPresent"