apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: quota-ns
  annotations:
    policies.kyverno.io/title: Add Quota
    policies.kyverno.io/category: Multi-Tenancy
    policies.kyverno.io/subject: ResourceQuota, LimitRange
    policies.kyverno.io/type: generation 
    policies.kyverno.io/description: >-
      Para tener un mayor control sobre el numero de recursos creados en un namespace es recomendable
      asignas recursos ResourceQuota o LimitRange. Esta política genera ambos recursos
      cuando se crea un namespace.      
spec:
  rules:
  - name: generar-resourcequota
    match:
      resources:
        kinds:
        - Namespace
    generate:
      kind: ResourceQuota
      name: resourcequota-default
      synchronize: true
      namespace: "{{request.object.metadata.name}}"
      data:
        spec:
          hard:
            requests.cpu: '4'
            requests.memory: '16Gi'
            limits.cpu: '4'
            limits.memory: '16Gi'
  - name: generar-limitrange
    match:
      resources:
        kinds:
        - Namespace
    generate:
      kind: LimitRange
      name: limitrange-default
      synchronize: true
      namespace: "{{request.object.metadata.name}}"
      data:
        spec:
          limits:
          - default:
              cpu: 500m
              memory: 1Gi
            defaultRequest:
              cpu: 200m
              memory: 256Mi
            type: Container

