apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  name: temp-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/megandil/kyverno-argocd.git'
    path: temp-app
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: temperaturas
  syncPolicy:
    automated: {}
