apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  name: policy-reporter-ui-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/megandil/kyverno-argocd.git'
    path: policy-ui-reporter-app
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: policy-reporter
  syncPolicy:
    automated: {}
