apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: temp-app
  namespace: argocd
project: default
source:
  repoURL: 'https://github.com/megandil/kyverno-argocd.git'
  path: temp-app
  targetRevision: HEAD
destination:
  server: 'https://kubernetes.default.svc'
  namespace: temperaturas
syncPolicy:
  automated: {}
ignoreDifferences:
  - group: kyverno.io
    kind: ClusterPolicy
    jqPathExpressions:
      - '.spec.rules[] | select(.name|test("autogen-."))'